# Global settings
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'prowzi-prod'
    region: 'us-west-2'

# Rule files
rule_files:
  - "rules/*.yml"
  - "alerts/*.yml"

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Scrape configurations
scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Prowzi platform services
  - job_name: 'prowzi-gateway'
    kubernetes_sd_configs:
      - role: pod
        namespaces:
          names:
            - prowzi-platform
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_label_app]
        action: keep
        regex: prowzi-gateway
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
        action: keep
        regex: true
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
        action: replace
        target_label: __metrics_path__
        regex: (.+)

  - job_name: 'prowzi-notifier'
    kubernetes_sd_configs:
      - role: pod
        namespaces:
          names:
            - prowzi-platform
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_label_app]
        action: keep
        regex: prowzi-notifier
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_port]
        action: replace
        target_label: __address__
        regex: ([^:]+)(?::\d+)?;(\d+)
        replacement: $1:$2

  - job_name: 'prowzi-agents'
    kubernetes_sd_configs:
      - role: pod
        namespaces:
          names:
            - prowzi-agents
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_label_component]
        action: keep
        regex: agent-runtime
      - source_labels: [__meta_kubernetes_pod_container_port_name]
        action: keep
        regex: metrics

  # Infrastructure monitoring
  - job_name: 'node-exporter'
    kubernetes_sd_configs:
      - role: node
    relabel_configs:
      - action: labelmap
        regex: __meta_kubernetes_node_label_(.+)
      - target_label: __address__
        replacement: kubernetes.default.svc:443
      - source_labels: [__meta_kubernetes_node_name]
        regex: (.+)
        target_label: __metrics_path__
        replacement: /api/v1/nodes/${1}/proxy/metrics

  - job_name: 'kube-state-metrics'
    static_configs:
      - targets: ['kube-state-metrics:8080']

  - job_name: 'kubelet'
    kubernetes_sd_configs:
      - role: node
    scheme: https
    tls_config:
      ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      insecure_skip_verify: true
    bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
    relabel_configs:
      - action: labelmap
        regex: __meta_kubernetes_node_label_(.+)

  # Database monitoring
  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s

  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s

  # Message queue monitoring
  - job_name: 'pulsar-exporter'
    static_configs:
      - targets: ['pulsar-broker:8080']
    metrics_path: /metrics
    scrape_interval: 30s

  # AI/ML model monitoring
  - job_name: 'ollama-metrics'
    static_configs:
      - targets: ['ollama:11434']
    metrics_path: /metrics
    scrape_interval: 60s

  # External service monitoring
  - job_name: 'solana-rpc'
    static_configs:
      - targets: ['solana-rpc-exporter:9100']
    scrape_interval: 30s

  - job_name: 'coingecko-api'
    static_configs:
      - targets: ['coingecko-exporter:9101']
    scrape_interval: 60s

  # Application-specific metrics
  - job_name: 'prowzi-sensors'
    kubernetes_sd_configs:
      - role: pod
        namespaces:
          names:
            - prowzi-sensors
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_label_type]
        action: keep
        regex: sensor
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
        action: keep
        regex: true

  - job_name: 'prowzi-analyzers'
    kubernetes_sd_configs:
      - role: pod
        namespaces:
          names:
            - prowzi-agents
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_label_type]
        action: keep
        regex: analyzer

  # Security monitoring
  - job_name: 'falco'
    static_configs:
      - targets: ['falco:8765']
    metrics_path: /metrics

  - job_name: 'cert-manager'
    kubernetes_sd_configs:
      - role: pod
        namespaces:
          names:
            - cert-manager
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_name]
        action: keep
        regex: cert-manager

# Remote storage configuration (for long-term storage)
remote_write:
  - url: "https://prometheus-remote-write.prowzi.com/api/v1/write"
    write_relabel_configs:
      - source_labels: [__name__]
        regex: 'prowzi_.*|go_.*|prometheus_.*'
        action: keep
    queue_config:
      capacity: 10000
      max_shards: 50
      min_shards: 1
      max_samples_per_send: 2000
      batch_send_deadline: 5s

# Recording rules for performance optimization
recording_rules:
  - name: prowzi.rules
    interval: 30s
    rules:
      - record: prowzi:agent_success_rate_5m
        expr: rate(prowzi_agent_tasks_completed_total[5m]) / rate(prowzi_agent_tasks_started_total[5m])
      
      - record: prowzi:sensor_data_freshness_5m
        expr: time() - prowzi_sensor_last_update_timestamp_seconds
      
      - record: prowzi:notification_queue_size_avg_5m
        expr: avg_over_time(prowzi_notification_queue_size[5m])

# Storage configuration
storage:
  tsdb:
    retention.time: 30d
    retention.size: 100GB
    wal-compression: true