apiVersion: apps/v1
kind: Deployment
metadata:
  name: adk-analysis-agent
  labels:
    app: adk-agent
    component: analysis
    version: v1.0.0
spec:
  replicas: 2
  selector:
    matchLabels:
      app: adk-agent
      component: analysis
  template:
    metadata:
      labels:
        app: adk-agent
        component: analysis
        version: v1.0.0
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: analysis-agent
        image: ghcr.io/prowzi/adk-analysis:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: ADK_MODEL
          value: "gemini-2b-flash"
        - name: AGENT_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NATS_URL
          value: "nats://nats.prowzi:4222"
        - name: RUST_RPC_HOST
          value: "agent-runner.prowzi:9090"
        - name: ADK_UI
          value: "disabled"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://tempo.monitoring:4318"
        - name: OTEL_SERVICE_NAME
          value: "adk-analysis-agent"
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        ports:
        - containerPort: 8080
          name: metrics
        livenessProbe:
          exec:
            command:
            - python
            - -c
            - "import asyncio; import nats; asyncio.run(nats.connect('nats://nats.prowzi:4222', connect_timeout=2))"
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
        readinessProbe:
          exec:
            command:
            - python
            - -c
            - "import asyncio; import nats; asyncio.run(nats.connect('nats://nats.prowzi:4222', connect_timeout=2))"
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: cache
          mountPath: /app/.cache
      volumes:
      - name: tmp
        emptyDir: {}
      - name: cache
        emptyDir: {}
      restartPolicy: Always
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
---
apiVersion: v1
kind: Service
metadata:
  name: adk-analysis-agent
  labels:
    app: adk-agent
    component: analysis
spec:
  selector:
    app: adk-agent
    component: analysis
  ports:
  - name: metrics
    port: 8080
    targetPort: 8080
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: adk-analysis-agent-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: adk-analysis-agent
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60