apiVersion: batch/v1
kind: CronJob
metadata:
  name: weight-updater
  namespace: prowzi
spec:
  schedule: "0 2 * * *"  # 2 AM daily
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: weight-updater
            image: prowzi/weight-updater:latest
            env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: prowzi-db
                  key: url
            - name: NATS_URL
              value: nats://nats:4222
            resources:
              requests:
                memory: "512Mi"
                cpu: "500m"
              limits:
                memory: "1Gi"
                cpu: "1000m"
