apiVersion: v2
name: prowzi
description: Always-on Crypto + AI Intelligence Platform
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: postgresql
    version: "12.12.10"
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: "18.6.1"
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: nats
    version: "1.1.5"
    repository: https://nats-io.github.io/k8s/helm/charts/
    condition: nats.enabled

maintainers:
  - name: Prowzi Team
    email: eng@prowzi.io

keywords:
  - ai
  - crypto
  - intelligence
  - monitoring
  - alerts

sources:
  - https://github.com/prowzi/prowzi

annotations:
  artifacthub.io/changes: |
    - kind: added
      description: Initial release
charts/prowzi/values.yaml:

yaml
# Default values for prowzi
global:
  image:
    registry: docker.io
    pullSecrets: []
  environment: production
  domain: prowzi.io
  storageClass: fast-ssd

# Gateway configuration
gateway:
  enabled: true
  replicaCount: 3
  image:
    repository: prowzi/gateway
    tag: latest
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    port: 80
    targetPort: 8080

  ingress:
    enabled: true
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/enable-cors: "true"
      nginx.ingress.kubernetes.io/websocket-services: "gateway"
    hosts:
      - host: api.prowzi.io
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: prowzi-tls
        hosts:
          - api.prowzi.io

  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi

  autoscaling:
    enabled: true
    minReplicas: 3
    maxReplicas: 10
    targetCPUUtilizationPercentage: 70
    targetMemoryUtilizationPercentage: 80

# Orchestrator configuration
orchestrator:
  enabled: true
  replicaCount: 2
  image:
    repository: prowzi/orchestrator
    tag: latest
    pullPolicy: IfNotPresent

  config:
    maxConcurrentMissions: 100
    defaultTokenBudget: 10000
    budgetRefillRate: 100  # tokens per second

  persistence:
    enabled: true
    size: 10Gi
    storageClass: fast-ssd

  resources:
    limits:
      cpu: 2000m
      memory: 4Gi
    requests:
      cpu: 1000m
      memory: 2Gi

# Sensor configurations
sensors:
  solana:
    enabled: true
    replicaCount: 2
    image:
      repository: prowzi/sensor-solana
      tag: latest
    config:
      rpcEndpoint: https://api.mainnet-beta.solana.com
      wsEndpoint: wss://api.mainnet-beta.solana.com
    resources:
      limits:
        cpu: 500m
        memory: 1Gi
      requests:
        cpu: 250m
        memory: 512Mi

  github:
    enabled: true
    replicaCount: 1
    image:
      repository: prowzi/sensor-github
      tag: latest
    config:
      rateLimit: 5000
      watchedRepos:
        - solana-labs/solana
        - ethereum/go-ethereum
        - openai/openai-python
    resources:
      limits:
        cpu: 250m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 256Mi

  arxiv:
    enabled: true
    replicaCount: 1
    image:
      repository: prowzi/sensor-arxiv
      tag: latest
    config:
      categories:
        - cs.AI
        - cs.LG
        - cs.CR

